resolver: lts-14.27
extra-deps:
  # miso-1.7.1.0
  - git: https://github.com/dmjio/miso.git
    commit: db5400ad7801076a8eac1c071a654b7317b78811
  - git: https://github.com/FongHou/servant-jsaddle.git
    commit: 2a45a6c9729328b8ccd330c902cc94aeda5af1d9
  - aeson-pretty-0.8.8
  - ghcjs-dom-0.9.4.0
  - ghcjs-dom-jsaddle-0.9.4.0
  - jsaddle-0.9.7.1
  - jsaddle-dom-0.9.4.1
  - jsaddle-warp-0.9.7.1
  - lens-aeson-1.1
  - rapid-0.1.4
  - ref-tf-0.4.0.2
  - validation-selective-0.1.0.0

flags:
  miso:
    jsaddle: true
